[MST-531] Allow creation of multiple active exam attempts
edx/edx-proctoring pull request #745
Opened 2021-01-06 21:10 UTC by bseverino

**Description:**

The `create_exam_attempt` function has been modified to allow multiple active attempts, as long as all other active attempts are in the `ready_to_resume` or `resumed` state. This saves the remaining time left in the new attempt, which is used to calculate the remaining time instead of the initial time limit.

**JIRA:**

[MST-531](https://openedx.atlassian.net/browse/MST-531)

**Pre-Merge Checklist:**

- [ ] Updated the version number in `edx_proctoring/__init__.py` and `package.json` if these changes are to be released.
- [ ] Described your changes in `CHANGELOG.rst`
- [ ] Confirmed Github reports all automated tests/checks are passing.
- [ ] Approved by at least one additional reviewer.

**Post-Merge:**

- [ ] Create a tag matching the new version number.

2021-01-07 16:31 UTC, schenedx reviewed
A way to make your change here easier to read is to make your branch PR against Michael's branch at `mroytman/MST-530-modify-attempt-endpoint`. This way, when Michael's PR is merged, you can just rebase your branch against master and create a new PR there.
That said, upon review your WIP logic here, I cannot see anything needs suggestion.

2021-01-08 15:42 UTC, schenedx requested changes
@bseverino Can we have more test cases?
in the test_api.py, can we add test case to create multiple resumed attempts for the same exam and user, then do a get API call to get all attempts successfully? And see if we are able to get all the resumed attempts?
Can we have similar test cases in test_views for a user who created an exam attempt, then update the exam attempt to error, then resumed the attempt, and getting the two attempts successfully?

2021-01-08 15:57 UTC, Zacharis278 approved these changes
lgtm

2021-01-08 20:03 UTC, alangsto requested changes
I think that this function https://github.com/edx/edx-proctoring/blob/0cf3076c4ed9cd9e6e37ea30936bf0ff89a4e2d4/edx_proctoring/api.py#L1879 may also need to be updated, so that the remaining time is accounted for in the exam length (so that the remaining time is actually enforced on the attempt)

2021-01-08 20:07 UTC, bseverino commented
@alangsto Thank you for catching that!

2021-01-11 18:32 UTC, alangsto approved these changes

2021-01-11 22:04 UTC, schenedx approved these changes
👍

2021-01-12 16:05 UTC, merged